import {createContext} from "react";

let initialState = {
    animations: ["animated-section-moveFromRight",
        "animated-section-moveFromLeft",
        "animated-section-moveFromBottom",
        "animated-section-moveFromTop",
        "animated-section-moveFromRight animated-section-ontop",
        'animated-section-moveFromLeft animated-section-ontop',
        'animated-section-moveFromBottom animated-section-ontop',
        'animated-section-moveFromTop animated-section-ontop',
        'animated-section-moveFromRightFade',
        'animated-section-moveFromLeftFade',
        'animated-section-moveFromBottomFade',
        'animated-section-moveFromTopFade',
        'animated-section-moveFromRight',
        'animated-section-moveFromLeft',
        'animated-section-moveFromBottom',
        'animated-section-moveFromTop',
        'animated-section-moveFromRight animated-section-ontop',
        'animated-section-moveFromLeft animated-section-ontop',
        'animated-section-moveFromBottom animated-section-ontop',
        'animated-section-moveFromTop animated-section-ontop',
        'animated-section-scaleUpDown animated-section-delay300',
        'animated-section-scaleUp animated-section-delay300',
        'animated-section-scaleUp',
        'animated-section-scaleUp',
        'animated-section-scaleUp',
        'animated-section-scaleUp',
        'animated-section-scaleUpCenter animated-section-delay400',
        'animated-section-moveFromRight animated-section-delay200 animated-section-ontop',
        'animated-section-moveFromLeft animated-section-delay200 animated-section-ontop',
        'animated-section-moveFromTop animated-section-delay200 animated-section-ontop',
        'animated-section-moveFromBottom animated-section-delay200 animated-section-ontop',
        'animated-section-flipInLeft animated-section-delay500',
        'animated-section-flipInRight animated-section-delay500',
        'animated-section-flipInBottom animated-section-delay500',
        'animated-section-flipInTop animated-section-delay500',
        'animated-section-scaleUp',
        'animated-section-rotateInNewspaper animated-section-delay500',
        'animated-section-moveFromRight',
        'animated-section-moveFromLeft',
        'animated-section-moveFromBottom',
        'animated-section-moveFromTop',
        'animated-section-rotatePullRight animated-section-delay180',
        'animated-section-rotatePullLeft animated-section-delay180',
        'animated-section-rotatePullBottom animated-section-delay180',
        'animated-section-rotatePullTop animated-section-delay180',
        'animated-section-moveFromRightFade',
        'animated-section-moveFromLeftFade',
        'animated-section-moveFromBottomFade',
        'animated-section-moveFromTopFade',
        'animated-section-rotateUnfoldLeft',
        'animated-section-rotateUnfoldRight',
        'animated-section-rotateUnfoldTop',
        'animated-section-rotateUnfoldBottom',
        'animated-section-rotateRoomLeftIn',
        'animated-section-rotateRoomRightIn',
        'animated-section-rotateRoomTopIn',
        'animated-section-rotateRoomBottomIn',
        'animated-section-rotateCubeLeftIn',
        'animated-section-rotateCubeRightIn',
        'animated-section-rotateCubeTopIn',
        'animated-section-rotateCubeBottomIn',
        'animated-section-rotateCarouselLeftIn',
        'animated-section-rotateCarouselRightIn',
        'animated-section-rotateCarouselTopIn',
        'animated-section-rotateCarouselBottomIn',
        'animated-section-rotateSidesIn animated-section-delay200',
        'animated-section-rotateSlideIn'
    ]
}

export const animationsContext = createContext(initialState.animations);